### ISSUE TITLE
Icons in toolbar are broken sometimes

### ISSUE THREAD

**Issue by c727** [home-assistant/ui-schema#10]
![unbenannt](https://user-images.githubusercontent.com/11984118/41569087-8123e324-7369-11e8-9e85-680e35eb1532.PNG)

**Comment by balloob** [comment]
Using MDI icons? Or Hass?

**Comment by c727** [comment]
`  - tab_icon: mdi:home-assistant`

**Comment by balloob** [comment]
Wonder if it's the stupid race condition again

**Comment by NeilCrosby** [comment]
I am also seeing this in 0.72, using `mdi` icons. At the current time, I have not yet seen any icons being loaded at all. I've tried in both Chrome and Safari in OSX, with a clean cache.

Happy to provide any more information as required.

**Comment by biacz** [comment]
i can fix it by clicking the debug icon that i created according to the documentation. once i click that, all icons appear.
