### ISSUE TITLE
Selectable default zoom on maps

### ISSUE THREAD

**Issue by DubhAd** [home-assistant/ui-schema#100]
The default zoom of the map cards are a little too close, showing the tracker and about 100 meters around them. While this may be appropriate in some cases, it's a bit close for tracking people to see where they are, as opposed to exactly which part of the building they're in ;)

It would be useful to have some control over the default or maximum zoom level on a card by card basis,

**Comment by balloob** [comment]
Let's allow controlling default zoom, I don't think maximum zoom should be configurable, that's up to the layer that is in use to decide what they support.
