### ISSUE TITLE
Hide name (or state) in picture-entity 

### ISSUE THREAD

**Issue by helto4real** [home-assistant/ui-schema#114]
I think it would be useful to be able to hide the name or state in picture-entity and center the one that is showing. 

Especially for example showing the presence state, there are no reason to show who it is if the picture already showing the person. I made a custom card for this but I think this is something that would be useful for more people as part of the "product". 

![image](https://user-images.githubusercontent.com/26500160/43013493-59a1fe28-8c49-11e8-93a7-07eb0df3ef3e.png)

**Comment by balloob** [comment]
If we allow name and state to be individually toggled, we should get rid of the `show_info` config option.

https://home-assistant-lovelace-gallery.netlify.com/#demo-hui-picture-entity-card
