### ISSUE TITLE
[Lovelace] Memory leak

### ISSUE THREAD

**Issue by bayi** [home-assistant/ui-schema#124]
After leaving running the home assistant tab with lovelace for a while ( approx. 10 hours ) the ui becomes more and more unresponsive, after another while ( after a day ) chrome kills the tab.

I attached a screenshot showing memory and cpu usage from the home assistant tab. It shows that ha is using more than 3 gigs of Ram with a constant 100% cpu. Usually a force refresh resolves the issue but it happens after some time again ...

![image](https://user-images.githubusercontent.com/3492831/43049817-7846927e-8dfe-11e8-9925-fe7205f32375.png)

**Comment by bayi** [comment]
This isnt happening with standard HA gui. Im also attaching my config maybe it helps.

[ui-lovelace.yaml.zip](https://github.com/home-assistant/ui-schema/files/2217358/ui-lovelace.yaml.zip)

**Comment by balloob** [comment]
Let me guess, you are embedding live camera streams that you would not have in the normal UI?

**Comment by bayi** [comment]
i had them in normal ui before ( 1 doorbird live camere + 1 doorbird last motion )

and they are on a different tab than i am looking at currently.

Never experienced this with the notmal UI before

**Comment by c727** [comment]
remove some cards and find the card-type that is causing issues

**Comment by balloob** [comment]
Closing for lack of feedback.
