### ISSUE TITLE
[Feature request] card filtering

### ISSUE THREAD

**Issue by moskovskiy82** [home-assistant/ui-schema#125]
Currently there is an entity filter card which can display entities with a certain state. 

But i would be extremely flexible to have a card filter. For example - what is the point of displaying AV receiver controls when it's off? In older UI this could be done with group visibility and automations. But as lovelace UI is a complete makeover - this feature is highly wanted.

Something like

      - type: glance
        visibility filter:
          - entity: temperature outside
             condition: below 25
        entities:
          - climate.balkon_convector
          - climate.balkon_floor

**Comment by balloob** [comment]
Already possible, see the 3rd example on https://home-assistant-lovelace-gallery.netlify.com/#demo-hui-entity-filter-card

**Comment by moskovskiy82** [comment]
@balloob it's not. Maybe it works on media player card but not in other cases.
The below config doesn't work properly

      - type: entity-filter
        entities:
          - media_player.onkyo
        state_filter:
          - 'on'
        card:
          type: glance
          entities:
            - media_player.kodi_cinema
            - input_number.zal_onkyo_volume
            - input_select.onkyo_mode
            - input_select.onkyo_dynvol
