### ISSUE TITLE
Glance for climate reports state, not temperature

### ISSUE THREAD

**Issue by reevery** [home-assistant/ui-schema#137]
I have a climate unit which glance is showing as state unit_of_measurement. The state is on/off, but the temperature is from another attribute. This therefore doesn't look right.
![image](https://user-images.githubusercontent.com/4381067/43196327-6e2585e0-8fff-11e8-8c5c-a3627b9411d5.png)
This is how it shows in state.
![image](https://user-images.githubusercontent.com/4381067/43196345-7ede5fd8-8fff-11e8-83ca-db6ca69e271a.png)

I think the best solution for my requirement would be being able to use templating in the value label, although I would also like to be able to use two lines. However this needs a fix as climate is (in my case, at least) on/off, not a temperature.

**Comment by c727** [comment]
create an issue to remove the uom attribute for climate https://github.com/home-assistant/architecture

**Comment by reevery** [comment]
Ok well in the main frontend it includes the temp, mode, and target temp too, which is (I guess) why it comes through.
![image](https://user-images.githubusercontent.com/4381067/43210138-39c2c3fe-9026-11e8-8054-48b30de4a933.png)
