### ISSUE TITLE
Improve Lovelace error log

### ISSUE THREAD

**Issue by poldim** [home-assistant/ui-schema#146]
So I've been getting a lot of the error below.  A quick look at the forums here or search on Google comes up with a lot of results with similar issues.  The only solution I've found is to disable everything on the view and trying bringing things back one at a time until error comes back.

Can the log capture more information as to the root cause of the failure?  For example, for me, this error was caused by several items that were not working:

* `camera.usps_mail`
* `sensor.usps_mail`
* `sensor.usps_packages`
* `sensor.fedex`
* `sensor.pws_weather`
* `sensor.pws_temp_f`
* `sensor.pws_relative_humidity`
* `sensor.pws_wind_string`

**Pssoble improvement:**
Have the error state something along the lines of:
> Lovelace UI is not able to retrieve data for `sensor.fedex` 

**Error as currently displayed in log**
> Log Details (ERROR)
> Thu Aug 02 2018 17:16:01 GMT-0700 (Pacific Daylight Time)
> 
> https://home.khaz.me/frontend_latest/app-6e4d53ede29a686d41a2bb0807ecd12c.js:445:3536 Uncaught TypeError: Cannot read property '_stateDisplay' of null

**Comment by grantclem** [comment]
Related issue #15801

**Comment by mr-sneezy** [comment]
I've been seeing these "Uncaught TypeError: Cannot read property '_stateDisplay' of null" errors also, but did not know they were related to unreachable sensors...

**Comment by poldim** [comment]
@mr-sneezy glad this was a useful post
