### ISSUE TITLE
Glance for climate

### ISSUE THREAD

**Issue by moskovskiy82** [home-assistant/ui-schema#148]
Climate component in the glance card doesn't show the temperature

![image](https://user-images.githubusercontent.com/15857592/43683748-d5008b40-989a-11e8-9568-7dbead2310f2.png)

**Comment by arsaboo** [comment]
How are you configuring the card?  Climate entities typically don't have temperatures in the state.

**Comment by jeradM** [comment]
The `state` of a climate entity is it's operation mode, not temperature. The units shouldn't be there and will be removed in an upcoming PR
