### ISSUE TITLE
Ability to define card overlay as tap_action

### ISSUE THREAD

**Issue by iantrich** [home-assistant/ui-schema#152]
I love the customization of lovelace so far but have found that the more-info cards are lacking some aspects I want or I just want them to feel more like lovelace.

I would like to propose that we add the ability to define a tap_action to show a defined card as an overlay.

**Comment by balloob** [comment]
More info dialogs are not part of the current scope of Lovelace. If more info dialogs are lacking, they should be fixed instead.
