### ISSUE TITLE
input_number (slider) changes appearance in 0.76.0b5

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/ui-schema#155]
Looks like i'm the Sliderman! :joy:

Opening a view, or refreshing a view shows the slider for a short time like this:
![auswahl_148](https://user-images.githubusercontent.com/26381449/44255021-fa6fcd00-a204-11e8-9c6d-6c8d67b8dbef.png)
and after a second or so like this:
![auswahl_149](https://user-images.githubusercontent.com/26381449/44255095-32771000-a205-11e8-8515-2d4e4cc2f5b5.png)
This happens not in all views, some show only the first appearance and i can't figure out what it depends on.

Like every issue i have with lovelace, only in Firefox, Chrome shows only the second appearance.

BTW, there's no chance to see what value the slider has, because of https://github.com/home-assistant/ui-schema/issues/150

**Comment by VDRainer** [comment]
At home in FF 61.0.1 on Ubuntu the issue is gone.
Sliders show normal.
In chrome they show without the value at the right.

**Comment by jer78** [comment]
They come and go for me on iOS.

**Comment by jeradM** [comment]
Which version of Ubuntu and Chrome are you running? I'll see if I can reproduce. 

The state text gets hidden if the overall width of the row is less than 350 px to make more room for the entity name, but it should happen faster than a second unless maybe the machine you are on is slow. And it could be that your firefox window is wider than your chrome window so the state is not hidden. Or Firefox is measuring the width of that div slightly larger

**Comment by VDRainer** [comment]
You're absolutely right. Making the chrome window wider shows the values at the end.
The issue showed on my laptop at work which is running ubuntu 14.04.
Will take a look tomorrow, but i think this can be closed.

**Comment by jer78** [comment]
Can we re-open this? Once the number disappears on iOS its gone for good. Shouldn't the name be moved to the top kinda like the input_select? Currently the only way I can see what I changed it to is create a sensor.

**Comment by balloob** [comment]
Open a new issue.
