### ISSUE TITLE
Card image is not updated when changed

### ISSUE THREAD

**Issue by pcopa** [home-assistant/ui-schema#157]
I've been using Lovelace for a few weeks and loving it. 

I'm using Hasssos Home Assistant 0.75.3 and ran into this issue:

I have a "picture card" with "image: /local/latest.jpg" and the image file "latest.jpg" is updated every 15 minutes by the pool controller, but the picture in Lovelace is never updated.  Even a browser refresh "CNT+F5" dose nothing.
Only changing the image name  will rest the picture.

Any help on this issue will be greatly appreciated.

`  - title: Pool
    cards:
      - type: picture-glance
        title: Test
        image: /local/latest.jpg
        entities:
          - sensor.p_ph
          - sensor.p_orp
          - sensor.p_ta
          - sensor.p_tw
`
The code formatting is not working for me. This is the code in plain text:
  - title: Pool
    cards:
      - type: picture-glance
        title: Test
        image: /local/latest.jpg
        entities:
          - sensor.p_ph
          - sensor.p_orp
          - sensor.p_ta
          - sensor.p_tw

**Comment by pcopa** [comment]
Thanks for the tip @jer78.  I tried it, but it seems to do the same.  
A Lovelace refresh will not reset the picture, but a "homeassistant.restart" **will** update the picture. 
This is strange, because i'm used to Lovelace updating everything with every view.

**Comment by balloob** [comment]
Everything in `/local` is cached indeed.

**Comment by pcopa** [comment]
Sorry for the formatting, but the Markdown syntax is deforming the text. ( I'm using Atom as editor, could that be the issue??)

The picture-entity is now updating the pictures with:

     - type: picture-entity
        entity: camera.local_file

in the "ui-lovelace.yaml" file and:

camera:
  - platform: local_file
    file_path: /local/latest.jpg

in the "configuration.yaml" file, But i'll have to work around the fact that picture-entity only shows one entity.
![lovelac02](https://user-images.githubusercontent.com/15312957/44360471-f05e0080-a488-11e8-92c3-162d597ea596.jpg)

**Comment by jeradM** [comment]
```yaml
- type: picture-glance
  camera_image: camera.local_file
  ...
```
