### ISSUE TITLE
State Text for climate entities in picture-entity does not include value

### ISSUE THREAD

**Issue by TheEggi** [home-assistant/ui-schema#159]
It seems that the state value, which is shown for climate entities is not including the value (like temperature), but it still shows the unit. 
Would it be possible to add the value for the given unit here?

![image](https://user-images.githubusercontent.com/1206407/44309854-1e7e0a80-a3cd-11e8-96a7-9aa4f39cd50f.png)

![image](https://user-images.githubusercontent.com/1206407/44309871-4ec5a900-a3cd-11e8-84ee-472c47879431.png)

**Comment by jeradM** [comment]
picture-entity shows the `state` of the entity which, for climate entities, is the operation mode. The temperature is an attribute. The units are going to be removed in the backend then they won't show up

**Comment by TheEggi** [comment]
Would it be an option to specify the text as a template? I mean otherwise the functionality seems to be quite limited. Or in another way: Is there any other way to achieve this ... other than building it on your own or using picture-elements?
