### ISSUE TITLE
Feature: Lovelace Picture Entity Height

### ISSUE THREAD

**Issue by randellhodges** [home-assistant/ui-schema#167]
It would be nice if there was a way to specify the height on the picture-entity. This way, if it takes a couple of seconds to get an image from a camera, you don't get things pushed around the screen after the image loads.

**Comment by balloob** [comment]
height is not the right config, as it depends on the width of the column. Ratio would work.

**Comment by randellhodges** [comment]
Yeah, ratio makes more sense. If I have time, I might see if I can figure out how to do it.

**Comment by randellhodges** [comment]
This has been implemented as aspect_ratio in 0.79.
