### ISSUE TITLE
Conditional cards in vertical stack take up space when hidden

### ISSUE THREAD

**Issue by john-ruddy** [home-assistant/ui-schema#169]
I stacked up a bunch of conditional cards with messages about the status of my gate sensors and found out they take up space even when they're not shown if they're inside a vertical stack
![image](https://user-images.githubusercontent.com/15241148/45974671-0e7ec980-c010-11e8-92a0-3fa32d8373a6.png)

I moved them outside the vertical-stack and the space went away. The margin space they take up is because of the css rule `#root > * { : 4px 0 8px 0; }` from the style tag inside the `hui-vertical-stack-card` element.

**Comment by john-ruddy** [comment]
On a related note, if a column in a horizontal stack contains only hidden cards it does not get hidden.

I understand that lovelace is in very early phases and that these seem like picky things to point out but I promise that I'm trying to be helpful not annoying. I do not think these issues are urgent.

**Comment by jeradM** [comment]
Geez stop being so annoying :wink: but seriously, this has been an issue for a while and I'll try to get it fixed today. I think this is a duplicate of #127, but I'm going to leave it open for now since it is specifically about the vertical-stack card so I don't forget to test it there

**Comment by john-ruddy** [comment]
My second comment is definitely a duplicate of 127 but I haven't dug into things far enough to know if they would be fixed by the same thing

**Comment by jeradM** [comment]
I suspect that fixing 127 will solve both of these issues

**Comment by iantrich** [comment]
Resolved: https://github.com/home-assistant/home-assistant-polymer/pull/1999
