### ISSUE TITLE
Feature request: add toggle button to glance cards

### ISSUE THREAD

**Issue by bmesuere** [home-assistant/ui-schema#174]
It would be nice to optionally add a toggle button instead of the status for things like lights or switches. I know you can add a toggle action to the card entity, but then you lose access to the info modal. For things like dimmable lights, I would like to have access to both.

Alternatively, the associated action could be split in 2 so that clicking the icon would show the info card and tapping the state label would perform the action/toggle.

**Comment by iantrich** [comment]
You can define the tap_action now, so I believe this is solved: https://www.home-assistant.io/lovelace/glance/#tap_action
