### ISSUE TITLE
state filter enhancements

### ISSUE THREAD

**Issue by turboc1208** [home-assistant/ui-schema#177]
I would like to see the ability to have a negative state filter ( not off for example).  Lights have a state of their brightness when they are on.  So using a state filter of "on" does not show the light as matching that criteria.
Being able to use a calculated or boolean comparison for the filter would be of benefit as well.  A state filter of " < 32" could be used to determine if the temperature is less than 32 (freezing).

These both could be done by using a template sensor to convert the value to an on/off value.  But it would be nicer to have it in lovelace.

**Comment by thomasloven** [comment]
This isn't the point in this discussion, but your example is not right. If you found a light that behaves that way, I think you should post a bug report.

When lights are on the state should be "on". The brightness value should be in the brightness attribute.

**Comment by balloob** [comment]
this is not something that would ever come to Lovelace. Lovelace is all about being able to statically determine which entities are involved in cards, wild cards do not fit in that vision. If you want such a thing, use one of the custom cards.

**Comment by turboc1208** [comment]
Balloob,
  First please adjust your tone of speech.  There is no reason to be rude or condescending in your response.  I am not asking for a wildcard.  I am asking for the ability to specify a static range state.  Lets take for example a door.  A door can either be open, closed, opening or closing.  I want the ability to include doors that are not closed.  I don't care about the other three states.  Yes I could just include all three values.  However in the case of temperature or other numeric value, having the ability to specify > or < when determining if the entity should be shown is I believe within the scope of a filter.
