### ISSUE TITLE
Sensor card configuration nomenclature inconsistent

### ISSUE THREAD

**Issue by Emacee** [home-assistant/ui-schema#180]
Now that I switched to a lovelace based UI in my Home-Assistant setup I came across the following inconsistency:

In the sensor-card it's title is configured by setting the 'name' whereas for all other card types with a configurable name this is done by setting the 'name'. 

See the screenshots for the current difference. 

<img width="872" alt="schermafbeelding 2018-10-19 om 23 39 06" src="https://user-images.githubusercontent.com/29025081/47245139-64b90f80-d3f8-11e8-8490-fca99b873473.png">
<img width="726" alt="schermafbeelding 2018-10-19 om 23 40 16" src="https://user-images.githubusercontent.com/29025081/47245140-64b90f80-d3f8-11e8-88b4-2b2efb177dc4.png">

**Comment by balloob** [comment]
Cards have titles, entities have names.

**Comment by zsarnett** [comment]
This seems like it needs resolved. The name refers to the name of the Card and therefore should be a title variable.
