### ISSUE TITLE
About the Gauge Card bug

### ISSUE THREAD

**Issue by EuropeJing** [home-assistant/ui-schema#182]
Gauge Card will out of range if the page width is not enough.
![tim 20181024235521](https://user-images.githubusercontent.com/25347249/47444657-8ac02480-d7e9-11e8-8b16-90744ae891aa.png)
![tim 20181024235532](https://user-images.githubusercontent.com/25347249/47444658-8ac02480-d7e9-11e8-8966-03de29e8de6b.png)

**Comment by zsarnett** [comment]
[Duplicate](https://github.com/home-assistant/home-assistant-polymer/issues/1765) 

Already tracked within polymer repo
