### ISSUE TITLE
Hide numeric keypad in Alarm panel when not used

### ISSUE THREAD

**Issue by arsaboo** [home-assistant/ui-schema#184]
The numeric keypad in the alarm panel card should be optional (or we should be able to hide it when codes are not used).  

Both my alarm panels don't use codes and the keypad is redundant. 

cc: @zsarnett

**Comment by balloob** [comment]
Then why would you use this card? Isn't the whole idea of the card the keypad ?

**Comment by arsaboo** [comment]
Not really. 

The card is to interact with security systems. Not every alarm system requires a code to arm/disarm. Codes are mostly optional. I casually browsed our alarm components and indeed most of them have `code` as optional (e.g., Simplisafe, Abode, Arlo, MQTT).

**Comment by zsarnett** [comment]
> The Alarm card by ciotlosm [here in the forum](https://community.home-assistant.io/t/lovelace-alarm-card/59831) has a "hide keypad" option. I tried but on the official card is not working. Is this a different implementation by someone else?

Yes.
