### ISSUE TITLE
Thermostat card should show the current operation

### ISSUE THREAD

**Issue by arsaboo** [home-assistant/ui-schema#188]
The icons in the thermostat cards do not indicate the current operation. For example, my thermostat is in `Away` mode as indicated by 

![image](https://user-images.githubusercontent.com/18319734/47736053-3206e680-dc44-11e8-8a63-49ba78969cb5.png)

The `away_mode` in the states confirm the same:

![image](https://user-images.githubusercontent.com/18319734/47736080-42b75c80-dc44-11e8-8dc1-fb8b544b77bd.png)

But the card does not indicate the same

![image](https://user-images.githubusercontent.com/18319734/47736097-4ba82e00-dc44-11e8-94e1-b044d2ea08a4.png)

We should use the attributes `away_mode` (to indicate whether we are in away mode or not) or `fan` (to indicate whether the fan is on/off) or `operation` to indicate (whether the thermostat is heating or cooling).

**Comment by iantrich** [comment]
@arsaboo is there some sort of precedence that would come into play here? With your example you currently have:
away_mode: on
fan_mode: auto
operation_mode: auto

What should be displayed in this case? Away and Auto and Auto? Too much text and what means what?

I think an indication of away/fan mode makes more sense if it is supported by the device

So in the case of away_mode, I probably don't care when it is off, but having a visual for when it on, makes sense. So when after Auto we could have an icon 
![image](https://user-images.githubusercontent.com/1287159/48529219-bb7b0300-e857-11e8-9bfc-972ee5d48a25.png) to indicate that. Same goes for fan_mode, I think.

**Comment by mrdje** [comment]
Same here, just trying the lovelace ui and I'm a bit disappointed that I cannot select "away_mode" anymore on the thermostat. :-/

Or maybe I just didn't look enough, there's maybe a possibility

**Comment by iantrich** [comment]
Text now reads "Auto - Away"
