### ISSUE TITLE
Homogenization of tap_action

### ISSUE THREAD

**Issue by thomasloven** [home-assistant/ui-schema#189]
Different cards and elements allow different `tap_actions`.

The currently available actions are 
- `more-info`
- `toggle`
- `call-service`
- `navigate`

Currently:

| | `more-info` | `toggle` | `call-service` | `navigate`|
|---|---|---|---|---|
| `picture-elements` | X | X | X | X |
| `  (service-button)` |   |   | X |   |
| `  (state-badge)` | | | | |
| `entities`| X | | | |
| `glance` | X | X | X | |
| `entity-button` | X | X | X | |
| `light`| * | * | | |
| `picture` | | | * | * |
| `picture-entity` | X | X | X | X |
| `picture-glance` | 1 | 1 | 2 | 2 |
| `sensor`| X | | | |

- All `picture-elements` elements support all actions except
  - `service-button` which only calls services
  - `state-badge` which isn't clickable
- `entities` card is locked to `more-info`
- `glance` card supports all but `navigate`
- `entity-button` card supports all but `navigate`
- `light` card is locked to `toggle` and `more-info`
- `picture` card supports `navigate` and `call-service` but with a different configuration method (**!**)
- `picture-entity` card supports `toggle` and `more-info`
- `picture-glance` card supports `navigate` and `more-info` (for cameras) but with a different configuration method (**!**) Icons are locked to `more-info` or `toggle` depending on type
- `sensor` card is locked to `more-info`

I may have missed something. This list is just from looking at the source, not testing...

Configuration is performed by setting the value of `tap_action` except in the case of `picture` and `picture-glance` card where `navigate` is used if `navigation-path` is set, and `more-info` is used if the picture source is a camera.

Regarding `call-service` all `picture-elements` elements add `entity_id:` to the data passed to the service. This limits the available services.

All this (except `picture`, `picture-glance`, `sensor`) applies to `hold_action` as well.

Some of the discrepancies makes sense (`light` card shouldn't be expected to work any other way) but some should probably be looked over.

### Related
- #191 
- #200

**Comment by balloob** [comment]
I agree that we should homogenize (what a word). But I also think that we should wait for UI to pan out a bit more.

Then I want to see if we can make it as similar across the board as possible. Maybe even enforce it by routing it all through the same helper, so we enforce same config.

**Comment by iantrich** [comment]
Let's toss this in here as well: https://github.com/home-assistant/ui-schema/issues/191 for once we are out of our feature freeze

**Comment by thomasloven** [comment]
Work is ongoing
home-assistant/home-assistant-polymer#2182

**Comment by thomasloven** [comment]
Updated table:

| | `more-info` | `toggle` | `call-service` | `navigate`| long-press |
|---|---|---|---|---|---|
| `picture-elements` | X | X | X | X | X |
| `  (service-button)` |   |   | X |   |   |
| `  (state-badge)` | | | | | |
| `entities`| X | | | | |
| `glance` | X | X | X | X | X |
| `entity-button` | X | X | X | X | X |
| `light`| X | X | | |
| `picture` | X | X | X | X | X |
| `picture-entity` | X | X | X | X | X |
| `picture-glance` | * | * | * | * | * |
| `sensor`| X | | | |

Everything that makes sense to use long-press now uses long-press (with possible exception of `entities` card), and thus supports all actions.
I'd call this done and will close the issue.
