### ISSUE TITLE
Add device tracker support to picture card

### ISSUE THREAD

**Issue by c727** [home-assistant/ui-schema#19]
it shows a map with a list of device_trackers

**Comment by balloob** [comment]
You're thinking too small again. 

Map card that has a list of entities. Will show the entities that have lat/longitude. Combine with entity-filter to just show device trackers.

**Comment by nlinnett** [comment]
Hi guys,

I've coded up a very basic solution for this, how should I share it so that others can see it? Should I share it here or in the forums?

Nigel

**Comment by c727** [comment]
well create a pull request

**Comment by nlinnett** [comment]
I don't think that what I have is ready to go into the project, I just wanted to share it for guidance, and to start discussion about creating custom cards.

Which repository should it be sent to? This one? I don't see any code files, so have no idea how to structure the filesystem.

**Comment by balloob** [comment]
You can create a [GitHub gist](https://gist.github.com/)

**Comment by nlinnett** [comment]
https://gist.github.com/nlinnett/d0671682de8bdffeb61d5b87ce140473

Okay, gist created. As I said it's a very basic implementation, and I still have things I would like to add to it. No need to be too gentle with feedback on it (if any).

1. Need to be able to put a title on it
2. I would like to be able to specify a colour for each entity that it tracks
