### ISSUE TITLE
:0:0 Uncaught errors from missing entities

### ISSUE THREAD

**Issue by jaburges** [home-assistant/ui-schema#190]
log shows:
`http://HA/lovelace/XXXX:0:0 Uncaught `

this error seems to occur when an entity in `ui-lovelace.yaml` doesnt exist.
Often can happen if re-naming something in the UI, or zwave renames the entity etc.

REQUEST:
can we include the entity that is missing in the error message please?

**Comment by balloob** [comment]
We already show error cards for missing entities so we can close this request I guess.

**Comment by edif30** [comment]
This should be re opened. This error is when an entity is configured but is not in HA at all. It is reproduced 100% of the time.

**Comment by zsarnett** [comment]
![image](https://user-images.githubusercontent.com/18730868/48316775-de868800-e5b5-11e8-8846-ce0139d7902a.png)

And we handle that

**Comment by edif30** [comment]
Let me get more info in a bit. There is a use case that isn't handled. I'm mobile so it will be a bit but an example I had recently was a cast device that went unavailable and then a restart was performed and upon HA coming up, the cast device was still not online. Therefore, Lovelace threw the uncaught error.
