### ISSUE TITLE
feature request: tap_action none

### ISSUE THREAD

**Issue by RezzZ** [home-assistant/ui-schema#191]
Hi, is it possible to add tap_action: none to cards? As hold_action also has the 'none' option, shouldn't this also be possible for taps?

Especially for glance cards I would like to disable tap_actions as the card is just to GLANCE at certain switch states (in my case). To prevent accidental turn off of the switch I would rather disable the taps entirely for these entities rather than creating template_sensors showing me the state of a switch.
Also, as icon_colors don't change for these template_sensors the 'tap_action: none' would be the better solution and reduces the nr of entities in HA.

**Comment by iantrich** [comment]
hold_action doesn't have a `none` option exactly, it's more so that if one is not defined, nothing is done while tap_action does have a default action. I think that is something we can add but we're currently in a feature freeze while stand up the UI editor.
