### ISSUE TITLE
Most of card does not fire the "toggle" action in HA 0.83.x, when accesing from Windows 10

### ISSUE THREAD

**Issue by sylas** [home-assistant/ui-schema#210]
After updating to 0.83.x, many cards do not not fire the "toggle" action, when accesing the Lovelace UI from Firefox or Chrome on Windows 10. Even at the HAGallery I can not turn on/off devices e.g. from the glance, entity-button, light and more cards (for the latter one, setting the brightness works, but toggle does not). From mobile devices everything works great, as usual.
It was also reported at the forum:
https://community.home-assistant.io/t/tap-action-on-glance-card-no-longer-working-after-upgrade-to-0-83-1
https://community.home-assistant.io/t/click-doesnt-work-in-ui-tap-does-wait-what-yes

**Comment by zsarnett** [comment]
https://github.com/home-assistant/home-assistant-polymer/issues/2085
