### ISSUE TITLE
Lovelace UI Editor Suggestions and Oversights. 

### ISSUE THREAD

**Issue by rxritalin** [home-assistant/ui-schema#218]
Just started using the UI editor for Lovelace today and short of stating good job, I wanted to point out a few things I noticed from a UX perspective. 
Obvious Omissions:
1.  Tab Order - There needs to be a simple way to reorder tabs. At present the only way I can see to do this is to delete all of the tabs and start building them again from scratch. From a UX perspective this is horrible. 

2. Tab View Variables - There seem to be some omissions in the Tab Creation window, like Panel and Background

3. Moving Cards Between Tabs - There should be a way to move and or copy Cards from one tab to another. I am aware that I can open a card, copy the code, create a new card in another tab and paste the code. This feels sloppy from a UX perspective though. Reminds me of that old trope of designers vs developers.

**Comment by zsarnett** [comment]
Next release adds Moving cards between Tabs. 

We have plans to add Duplicating of cards.

Good Catch on the Tab View Variables

Will look into Moving Views

**Comment by balloob** [comment]
Closing this as some things are done, others are worked on.
