### ISSUE TITLE
FR : Ability to change Icon color based on state

### ISSUE THREAD

**Issue by Digitalcheffe** [home-assistant/ui-schema#222]
Would like to be able to change icon color based on entity state.

There is currently a custom button card that has similar feature set.

https://github.com/kuuji/button-card

![image](https://user-images.githubusercontent.com/10412901/50672430-18687f00-0fa6-11e9-8499-c22d6d5faee6.png)

**Comment by Digitalcheffe** [comment]
Yeah i saw that as an option picture elements, that would work out  as well since state_filter is probably a better fit for other cards as well.

**Comment by JustinDwy** [comment]
even just changing the icon based on state would be useful.

**Comment by iantrich** [comment]
More history here
