### ISSUE TITLE
Raw config editor

### ISSUE THREAD

**Issue by bstrakt** [home-assistant/ui-schema#225]
I'm doing my edits in ui-lovelace.yaml and pasting the content in Config raw editor. This method worked until version 0.85, where Resources are discarded.

In version 0.85, if I'm pasting the contents from ui-lovelace.yaml to Configure UI - Raw config editor, the Resources are discarded and custom cards are not loaded:

Example from .storage/lovelace before 0.85:
{
    "data": {
        "config": {
            "resources": [
                {
                    "type": "module",
                    "url": "/local/custom_ui/monster-card.js"
                },
                {
                    "type": "module",
                    "url": "/local/custom_ui/jukebox.js"
                }
            ],
            "title": "bla bla",
            "views": [
                {
                    "cards": [
                        { 
....
Example from .storage/lovelace in 0.85:
{
    "data": {
        "config": {
            "title": "Home Sweet Home",
            "views": [
                {
....

Contents of ui-lovelace.yaml:
title: bla bla
resources:
  - url: /local/custom_ui/monster-card.js?v=0.1
    type: js
  - url: /local/custom_ui/jukebox.js
    type: module
views:
  - icon: mdi:home-heart
    id: HomeStatus
    title: bla bla
    cards:
       ......

**Comment by balloob** [comment]
Fixed in https://github.com/home-assistant/home-assistant-polymer/pull/2439
