### ISSUE TITLE
Possible to extend the "secondary_info" line to include entity attributes

### ISSUE THREAD

**Issue by finity69x2** [home-assistant/ui-schema#230]
As the title suggests would it be possible (or is there a plan) to extend the secondary_info of an entity to allow additional attributes of that entity?

Or even better to allow an attribute of any entity at all?

My use case is showing battery levels and/or calendar dates in the google calendar entity on the frontend under the entity.

I can do it now using the custom-ui by andrey but it doesn't seem to work in lovelace.

**Comment by zombiehunter1** [comment]
I would really love this also, I have battery levels shown as Good or Replace biased on battery level %, it would also be good to show the raw percentage sensor as secondary_info

**Comment by balloob** [comment]
We are not planning on implementing this feature. it has been discussed before here: https://github.com/home-assistant/home-assistant-polymer/pull/2089

Decision is final.
