### ISSUE TITLE
Add sensors to picture-glance card

### ISSUE THREAD

**Issue by balloob** [home-assistant/ui-schema#24]
This will allow the glance card to be exactly like the plant card.

We can then migrate the `plant-info` card to just render a glance card.

**Comment by zsarnett** [comment]
What do you mean by banner?

**Comment by balloob** [comment]
This is the plant card. The picture is the banner.

![image](https://user-images.githubusercontent.com/1444314/48085636-1d55c000-e1fb-11e8-98ed-d7a9e069efe8.png)

**Comment by balloob** [comment]
However, this is an old issue. I wonder if this is what we want or do we want to enhance the picture glance card with labels below the sensors, as we discussed recently.

**Comment by zsarnett** [comment]
I think enhancing the picture glance card then migrating the plant card to that would look better.

**Comment by iantrich** [comment]
Closing in favor of https://github.com/home-assistant/ui-schema/issues/104
