### ISSUE TITLE
How to deal with non-existing entities

### ISSUE THREAD

**Issue by balloob** [home-assistant/ui-schema#26]
In https://github.com/home-assistant/home-assistant-polymer/pull/1322#pullrequestreview-131207237 we added a stop-gap fix to prevent cards from crashing when an entity does not exist. This fix will skip the entity if it doesn't exist instead of crashing.

With Lovelace we have taken the stance that we should fail visibly when things are misconfigured. To that end, we need a better solution. I think that we need to look on a per-card basis how to deal with this.

Example: `entity-picture` should just show the title overlay and behind the entity name add a (not found) text.

**Comment by c727** [comment]
I think most cards handle this now
