### ISSUE TITLE
[Feature Request] Name/title for horizontal- and vertical stack

### ISSUE THREAD

**Issue by Smiggel** [home-assistant/ui-schema#264]
I would like to be able to add an title to a horizontal and vertical stack. Now I am not able to do this and get items like in the the attachment:

<img width="378" alt="Schermafbeelding 2019-04-28 om 17 39 44" src="https://user-images.githubusercontent.com/1825953/56867169-86680480-69e2-11e9-8884-191a9a1cec9f.png">

I would be nice to be able to have a header above the cards.

**Comment by thomasloven** [comment]
Possible solutions:

- https://github.com/custom-cards/vertical-stack-in-card
- https://github.com/thomasloven/hass-config/wiki/Misc-tricks#cardelemententity-row-triality
