### ISSUE TITLE
[Feature Request] add hvac_action to thermostat card

### ISSUE THREAD

**Issue by jarzebskim** [home-assistant/ui-schema#266]
**Is your feature request related to a problem? Please describe.**

as described in this issue:

https://github.com/home-assistant/home-assistant-polymer/issues/3382

**Describe the solution you'd like**
I'd like to have info in thermostat card if heating is currently on or off. In every form as you like. Maybe mode and action in separate lines? Or icons that will show current mode?  

Thanks.

**Comment by balloob** [comment]
Fixed in 0.96.4

**Comment by jarzebskim** [comment]
actions are not localized. Can I translate it somehow?

**Comment by balloob** [comment]
Translations are managed in Lokalise. Please see the instructions here: https://home-assistant.io/developers/frontend_translation
