### ISSUE TITLE
Lovelace: Wrap text in glance card

### ISSUE THREAD

**Issue by arsaboo** [home-assistant/ui-schema#28]
The picture card only uses one line of text currently. 
![image](https://user-images.githubusercontent.com/18319734/41792469-f5cc5930-7626-11e8-81bd-729695c849d2.png)
We should wrap text in the picture card.  While we are at it. it may also be nice to evenly space out the entities in the card.

**Comment by c727** [comment]
Text overflow with multiline is complicated.

I also like to keep the 5 elements per row to have some consistency among all `glances` cards

**Comment by jackjohnsonuk** [comment]
Would this wrap text for the "state" as well as the entity?

**Comment by c727** [comment]
In 0.73 you can set a custom title. Multiline is difficult
