### ISSUE TITLE
Lovelace: Glance card does not scale entity_picture correctly

### ISSUE THREAD

**Issue by arsaboo** [home-assistant/ui-schema#29]
Typically, the entity_picture is scaled to appear nicely in a circle. That does not seem to be the case in the glance card

![image](https://user-images.githubusercontent.com/18319734/41793745-0ce4e96c-762b-11e8-8596-35d0f98298f3.png)

**Comment by bayi** [comment]
Hi, just wanted to report this ;)

This is a style issue only the following fixes it:

under hui-glance-card:
Remove the "width: 100%;" from the state-badge item. Now the images are fine again but arent centered, this fixes that:
.entities .entity {
  align-items: center;
}



I still didnt figured out where to modify theese styles, hope this will help to fix it faster.
