### ISSUE TITLE
Feature Request: Glance card: Add option to hide labels and/or values

### ISSUE THREAD

**Issue by bayi** [home-assistant/ui-schema#33]
Often the values and/or labels arent needed in a glance card. 

For example here i have a glances glance ( o.O ) card display my servers system information:
![image](https://user-images.githubusercontent.com/3492831/41825213-de0755c8-781c-11e8-965d-2fad9cfb61c1.png)
I would get rid of the name of the entities as the icons are clearly representing the type of the value.

And here for example ( device tracker ) : 
![image](https://user-images.githubusercontent.com/3492831/41825231-28052efc-781d-11e8-830a-f3bb0238eee3.png)

Im already displaying with an entity-filter the only devices that are "Home" (Otthon in the picture) i dont need to display the value explicitly.

Hope this can be implemented and thank you can keep up the amazing work.

**Comment by c727** [comment]
"would get rid of the name of the entities as the icons are clearly representing the type of the value." Good argument for someone that is using the same icon for 5 entities...

**Comment by bayi** [comment]
valid, but im in the middle of customizing the icons :)

**Comment by poldim** [comment]
I started messing around with LL yesterday and made a few glances cards. Since I'm using entity filtering, I don't need them to show the state of ON or OPEN since it's redundant to the card filter and title. 

So, I would love to be able to hide the state value.
