### ISSUE TITLE
Allow custom entity naming

### ISSUE THREAD

**Issue by rogro82** [home-assistant/ui-schema#36]
It would be nice to allow defining custom entity names (titles).

Most of my entities are named after their location e.g. "Kitchen motion" and "Kitchen light". It would be nice if they can be put in a group "Kitchen" and then just name them "motion" and "light". So basically instead of just specifying an entity-list in cards also allow for local customizations of the specified entities.

**Comment by bayi** [comment]
i did the same but used the inbuil "Customization" tab for this. The entity ids stayed the same so i could still filter for example "lights.light_workroom*" while had the names for the workroom lights simply as "Desk" etc and not "Workroom Desk".

**Comment by rogro82** [comment]
That works for entities you only want show using that name, but I have around 10 motion-sensors which are named "[Room] motion". I want to show them locally in a group for its room (e.g. Kitchen) with just the name "Motion" and in a group "Motion" using only the room name.

Besides that I still want them to show up in history with their full-name. 

In my opinion the current entity_id and friendly_name are good for back-end ids ( to use in automations and to specify the friendly name shown in the history ). Adding local naming ( and perhaps allowing more local entity  customizations ) would make the UI a lot cleaner

**Comment by victorcerutti** [comment]
I have the exact same need. 
I really enjoy playing with Lovelace and I think it's a huge improvement but I'm stuck with the same issue.
It's even more needed when using `glance` card as the name is stripped after a few characters.

Local **name** or **alias** is much needed

**Comment by MizterB** [comment]
Agreed - having the ability to override the name based on the context in which it is presented would be very beneficial.

**Comment by jeradM** [comment]
This has been added to the glance card, should be straightforward now to add it to the enitites card. @c727 you can assign this to me if you want and I'll do it after work.
```yaml
cards:
  - type: glance
    title: Kitchen
    entities:
      - entity: sensor.kitchen_motion
        title: Motion
      - light.kitchen_light #Simple syntax still supported
```

**Comment by quthla** [comment]
Would be nice to have that for history-graph too
