### ISSUE TITLE
Ordering Cards

### ISSUE THREAD

**Issue by jackjohnsonuk** [home-assistant/ui-schema#38]
Is it possible to predetermine which order the cards are shown in? 

I think it'd be great to have users to have some uniformity in how they layout their views.

i.e. I have my views divided by rooms and I'd love the room's camera to be top left, lights middle, switches right etc...

**Comment by c727** [comment]
https://github.com/home-assistant/ui-schema/issues/25

**Comment by jackjohnsonuk** [comment]
Sorry, missed that one!

Thanks

Jack
