### ISSUE TITLE
"Camera Glance"

### ISSUE THREAD

**Issue by jackjohnsonuk** [home-assistant/ui-schema#39]
Is it possible to have a "Camera Glance" as well as a picture glance?

**Comment by balloob** [comment]
Instead, we should allow setting a camera as a source picture for the picture glance. 

Camera pictures are fetched like this https://github.com/home-assistant/home-assistant-polymer/blob/master/src/cards/ha-camera-card.js#L102-L116

**Comment by jackjohnsonuk** [comment]
Great idea! I'm no coder but will have a play see if I can help

**Comment by luci-11** [comment]
Don't know if it could be helpful but doing this works until token changes:

just open the camera card, right click on it, "copy image URL".
Then use picture-glance and put as image that URL (from /api/camera_proxy_stream/....).

**Comment by luci-11** [comment]
Good Update. 
Token problem can be skipped using 
`image: /api/camera_proxy_stream/camera.ffmpeg?api_password=xxx`

See pic (Stream is from a raspicam):
![image](https://user-images.githubusercontent.com/25179041/41963821-d0f1749e-79f8-11e8-99f7-3a2699628ff4.png)

**Comment by kflinderman** [comment]
So I've done this, but my problem with it is that it doesn't update the picture-glance as it would the camera tile.  The only way I can get it to update is to refresh the page (and not just lovelace). It'd also be nice to be able to click the photo and get the same focus in that we get from the camera tile.

**Comment by luci-11** [comment]
@kflinderman  "I can get it to update is to refresh the page (and not just lovelace)"  this is strange, I have continuous streaming.   What I did is login to classic HA, then go to lovelace URL and relogin.
Let me know.
About second part, I can't help

**Comment by jeradM** [comment]
@c727 you can assign this to me
