### ISSUE TITLE
Lovelace error screen

### ISSUE THREAD

**Issue by balloob** [home-assistant/ui-schema#40]
When we have invalid YAML or the file is not found, we show an error screen. This error screen should contain a refresh button to refresh the config.

**Comment by c727** [comment]
... to refresh the whole panel?!

**Comment by balloob** [comment]
Yes, we need to fetch the latest config because user might have fixed YAML error or created the file.

https://github.com/home-assistant/home-assistant-polymer/blob/master/src/panels/lovelace/ha-panel-lovelace.js#L35-L42
