### ISSUE TITLE
Permalinks for views

### ISSUE THREAD

**Issue by balloob** [home-assistant/ui-schema#42]
When a user selects a view, we should update the url.

Right now, views do not have unique IDs. We can either introduce an id field or we can use the array index. Only downside of the array index is that adding a view will mess up all indices that came after the position where the new view was introduced.

**Comment by balloob** [comment]
So when we read a ui-lovelace.yaml file, and when we find a view without an ID, should we just add IDs and write the file to disk and then return it to the user ? 

After that the user can change the IDs.

Frontend url for now will be `/lovelace/<ID of view>`, so for example `/lovelace/kitchen`

**Comment by andrey-git** [comment]
Doesn't writing yaml kills comments?

Make the id optional. If it is missing either use title (escaped) or don't put it in the URL at all.

**Comment by c727** [comment]
name can be anything like an emoji. `view.id || index` is an option I think

**Comment by balloob** [comment]
Ah yes, writing YAML will kill comments :(

The problem when we don't reflect the current view to the url is that the behavior of the back button is unexpected. Sometimes it will work, sometimes it won't.

We can add a card to the view to notify the user if an ID is missing. That way we offer solutions on correct behavior.
