### ISSUE TITLE
Add config support to state-cards (custom_ui)

### ISSUE THREAD

**Issue by cdce8p** [home-assistant/ui-schema#44]
Since the `entities` card type is basically the old group, it might make sense to still support `custom_ui` state cards. Maybe as an option in the advanced config described here: https://github.com/home-assistant/ui-schema/issues/43#issuecomment-400109139?

**Comment by balloob** [comment]
The idea of lovelace is that we don't store any UI configuration in the state machine

**Comment by balloob** [comment]
So we will support custom UI as described in the config, but the custom elements require some slight changes compared to the old custom UI API.(more info in the docs but can't link as I'm on my phone)
