### ISSUE TITLE
Entity filter: sort by name

### ISSUE THREAD

**Issue by ciotlosm** [home-assistant/ui-schema#47]
Allow ordering of entities within cards (glance, entities, etc) where you have multiple entities based on attributes

**Comment by c727** [comment]
what's the usecase? entities are sorted FIFO

**Comment by ciotlosm** [comment]
I think I made the wrong use case :-) I think ordering is more useful when you're using entity-filter and you want some ordering based on attributes.

**Comment by balloob** [comment]
Since we don't allow any ordering currently, we should order by the output of `computeStateName()`. After that we could add `order: "attribute:bla"`, `order: state`, `order: name`

**Comment by balloob** [comment]
We've slimmed down the entity filter options to just filter on states on a pre populated group of entities. This feature request is no longer relevant as you can decide on the order of your entities yourself.
