### ISSUE TITLE
Glance: force toggle state

### ISSUE THREAD

**Issue by ciotlosm** [home-assistant/ui-schema#49]
Allow for an option on glance to support toggling of entities (that support toggle) like picture-glance without the need to open more info dialog

**Comment by c727** [comment]
balloob said in a group of entities all entities shall have to same action. to it will be toggle only or dialog only

**Comment by ciotlosm** [comment]
That should be enough for start, gives people the flexibility.

**Comment by balloob** [comment]
Maybe a config option that is `tap-action: more-info/toggle` ?
