### ISSUE TITLE
Picture-glance: Consistency for entities opening more info dialog

### ISSUE THREAD

**Issue by ciotlosm** [home-assistant/ui-schema#53]
Right now clicking entities in picture-glance can produce unexpected results. Most of toggle enabled entities trigger on/off, but some sensors open more info dialog.

However there are entities that trigger on/off even if they should not allow that, but are more suitable for more info dialog. Examples: climate, alarm, etc.

Suggestion: Either disallow entities that don't have binary state or on/off from the card, or allow for more info dialog based on domain and document this in the entity.

**Comment by c727** [comment]
https://github.com/home-assistant/home-assistant-polymer/pull/1339
