### ISSUE TITLE
Views & cards: use either title or name attributes

### ISSUE THREAD

**Issue by ciotlosm** [home-assistant/ui-schema#54]
Cards use title, views use name. Some users reported it's confusing for new starters and would be better to use just one approach instead. 

Use case: faster adoption and less issues due to confusion

**Comment by balloob** [comment]
Which one would you prefer?

The reason I use `name` for view is because it doesn't prescribe how it will be used. With `title`, you can expect it to be only used for `title`

**Comment by ciotlosm** [comment]
I think `title` is more used, but I agree with your argument as well. I raised this based on feedback. I could live with title vs name as view you don't touch that much
