### ISSUE TITLE
Card header: Fix padding and color

### ISSUE THREAD

**Issue by c727** [home-assistant/ui-schema#57]
header color and padding don't match with our entities card
![unbenannt](https://user-images.githubusercontent.com/11984118/42069198-ac06a574-7b50-11e8-9f9d-fa1279c5cb2b.PNG)

**Comment by balloob** [comment]
I fixed the padding already. When a header is defined, we should not have a padding-top of 16 pixels. https://github.com/home-assistant/home-assistant-polymer/pull/1369/files#diff-93b6d3d2585ff7897d81449b1a874572R25
