### ISSUE TITLE
Option for fitting all cards to screen size

### ISSUE THREAD

**Issue by stiansoevik** [home-assistant/ui-schema#58]
Suggestion: an option which fits all cards in a view to the display size, without requiring any scrolling. This can be achieved by resizing the cards, and optionally removing padding etc.

The reasoning behind this, is the use case where a tablet presents a UI mostly for informational purposes. My initial tests of Lovelace consisted of displaying a camera image and weather forecast on a 7" tablet. The cards stacked on top of each other, forcing me to scroll, and after adding new cards (which resulted in two columns), I still have to scroll in order to see all data.

**Comment by c727** [comment]
Create a custom panel with a grid then

**Comment by stiansoevik** [comment]
Do you mean instead of using Lovelace UI, or is that a possibility within Lovelace? I think it anyways is relevant to raise an issue about how the automatic layout behaves, as it could utilize the screen better.
