### ISSUE TITLE
Apply themes to tabs too

### ISSUE THREAD

**Issue by balloob** [home-assistant/ui-schema#6]
The current theme of a view should be applied to the whole ha-app-layout, including tab bar and header.

**Comment by c727** [comment]
I'm not sure if we want this. Some have automations for changing themes on day/night that we break here.

I think it's fine if we still use the main theme and for our views and cards we can use incremental themes that only change specific color variables

**Comment by balloob** [comment]
I guess you're right. It will get very messy if two themes don't overlap completely
