### ISSUE TITLE
glance: does not render when  specifying a title 

### ISSUE THREAD

**Issue by gnkarn** [home-assistant/ui-schema#60]
- type: glance
        title: 
        entities:
          - device_tracker.homeassistant_gusphone
          - device_tracker.homeassistant_marcephone
          - entity: sensor.alarma_zona
            title: zona

the last entity does not get rendered , when the title or name is given , this is super important feature in order to "shorten" the entity printed names..

**Comment by c727** [comment]
requires HA 0.73
