### ISSUE TITLE
Allow hiding title in stack cards

### ISSUE THREAD

**Issue by arsaboo** [home-assistant/ui-schema#63]
Given that stack cards are smaller than a full size cards, displaying titles on them sometimes look bad, e.g.:

![image](https://user-images.githubusercontent.com/18319734/42137989-f9d014da-7d43-11e8-935a-9c9cf714ecf1.png)

Since the state is known from the image itself, it will be nice to have an option to hide titles.

**Comment by c727** [comment]
Yes, we can't adapt all our cards to 20% width only. horizontal stack should be only used for picture only or custom cards
