### ISSUE TITLE
Support mdi icons wherever image is available

### ISSUE THREAD

**Issue by arsaboo** [home-assistant/ui-schema#64]
We should support mdi icons wherever `image` option is available. For example, in the stack cards or in the glance cards, mdi icons are often perfect solutions to simple things like (volume, lights).

**Comment by balloob** [comment]
I am a bit confused. Images are big, lots of detail. Icons are simple? In the stack cards, we only support cards, we don't support any image?

**Comment by arsaboo** [comment]
I see the point. Images can always to be used in place of mdi icons. Closing the issue.
