### ISSUE TITLE
History Graph: Override Chart Options Via Lovelace Config

### ISSUE THREAD

**Issue by MizterB** [home-assistant/ui-schema#66]
Right now, all of the History Graph config options are hard-coded into the chartOptions variable in state-history-chart-line.js and state-history-chart-timeline.js. Would it be possible to extend these charts to allow Lovelace config values to override these default settings, and ideally allow additional settings that are supported by Chart.js?

The ability to customize colors, tick mark labels, time units, min/max ranges, etc. would be very helpful!

**Comment by balloob** [comment]
I am not sure if this is something we should want in Lovelace, or that someone should make a custom card for this. If we expose this, our charting lib is no longer an implementation detail.

**Comment by zsarnett** [comment]
Closing. We have hours to show and thats about all we should expose
