### ISSUE TITLE
Incorrect filter config

### ISSUE THREAD

**Issue by omriasta** [home-assistant/ui-schema#73]
![screenshot from 2018-07-03 13-44-31](https://user-images.githubusercontent.com/11823048/42235939-4c04e6ac-7ec7-11e8-81ea-3acf69eae45d.png)
Sorry about the screenshot but can't copy the text in my browser.
I followed the instructions to get started with lovelace and I received the same error regarding incorrect filter config. I copied some of the other samples posted here and no matter what I do the filter card will not work. Currently on Hassbian with 0.73b4
All the other cards working fine except for filter.

**Comment by c727** [comment]
check the latest docs. filter was reworked

**Comment by omriasta** [comment]
Was able to get that to work but having issues with camera preview now. Do you have a link to the latest docs?
