### ISSUE TITLE
Keep space between vertical stacked cards

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/ui-schema#74]
Looks nicer, i think!
Default UI
![auswahl_132](https://user-images.githubusercontent.com/26381449/42318839-890616a4-8050-11e8-9cd2-5a24df086a68.png)
Lovelace vertical stacked
![auswahl_133](https://user-images.githubusercontent.com/26381449/42318878-9fff97c2-8050-11e8-8f63-8bd86b064643.png)

**Comment by c727** [comment]
If you use Firefox enable shadowroot and custom elements in experimental features
