### ISSUE TITLE
Allow generic image options on the picture-elements card

### ISSUE THREAD

**Issue by arsaboo** [home-assistant/ui-schema#75]
Our current `picture-elements` card supports `service-button`, `state-icon`, `state-badge`, and `state-text`. This limits what we can add to the card. For example, here's how a camera looks on the card:

![image](https://user-images.githubusercontent.com/18319734/42332541-3e48a8d4-8046-11e8-8cf5-4f6ddee7625b.png)

Not only does not not look pretty there, the small image there is quite useless. I would much rather have an image that also provides more flexibility in terms of what I can add there and matches with the other parts of the image (something like the following):
![image](https://user-images.githubusercontent.com/18319734/42332629-80a3b2d2-8046-11e8-91b2-79ddeaaf452f.png)

As such, it will be nice to have an option to add a generic picture element that can be updated based on the state. Basically, the functionality provided by our `picture-entity` card inside the `picture-elements` card (not sure if I am using the right terminologies). Specifically:
1. Use the image based on the state of the entity
2. Specify tap-action (open more-info cards, when toggle not supported)

A casual look at the [Floorplan thread ](https://community.home-assistant.io/t/share-your-floorplan/21315) highlights that most folks are adding visual elements on these cards. Some use cases:
1. Differentiate between different types of lights or doors. For example, table lamp should look different than the outdoor lights. For example, this can be much better:

![image](https://user-images.githubusercontent.com/18319734/42333272-4cc08272-8048-11e8-867f-f08dd8fc0646.png)

2. Visually indicate if the TV or any device is ON or OFF. For example, instead of using this icon to present my TV,

![image](https://user-images.githubusercontent.com/18319734/42333360-890b8de4-8048-11e8-9d82-7ae426ebe5ea.png)

I would much rather have something like this (and change that image based on the TV state):
![image](https://user-images.githubusercontent.com/18319734/42333345-7f87b108-8048-11e8-8bf2-196c789e9ce3.png)

Heck, that would make even something like this possible:

![](https://community-home-assistant-assets.s3-us-west-2.amazonaws.com/original/3X/c/d/cd97b8c709f47e0349429b4ccc2d3e273cde6d64.gif)

**Comment by balloob** [comment]
I like it. Should be fairly easy using the hui-image tag

**Comment by jeradM** [comment]
I did some work on this and came up with this using an image element type (using hui-image) with state_image. It's not as pretty as what @arsaboo posted, but it's a start. I'll try to get a PR in for this sometime this weekend.

https://gfycat.com/ParchedDefiniteAmazontreeboa

**Comment by arsaboo** [comment]
That is great...look forward to this. BTW, are you replacing the image based on state (it will be nice to be able to do that) there or only filter?
