### ISSUE TITLE
Media Controller: Option to filter by state

### ISSUE THREAD

**Issue by Bahnburner** [home-assistant/ui-schema#78]
Currently in the old Hass UI, I have a script to hide paused or stopped media players from the default view. It would be awesome to be able to use the entity filter card on media controllers to only display them if they're actively playing.

**Comment by Bahnburner** [comment]
Thanks for the info. I attempted method #2 previous to my feature request, but it results in an error. I assumed this certain configuration wasn't available, so I made this feature request. 

    Cannot read property 'states' of undefined
    
    {
      "type": "entity-filter",
      "entities": [
        "media_player.rasplex"
      ],
      "state_filter": [
        "playing"
      ],
      "card": {
        "type": "media-control",
        "entity": "media_player.rasplex"
      }
    }

and here's the portion from my config: 

          - type: entity-filter
            entities:
              - media_player.rasplex
            state_filter:
              - 'playing'
            card: 
              type: media-control
              entity: media_player.rasplex

**Comment by balloob** [comment]
That's a bug, please report as a new issue. That should work.
