### ISSUE TITLE
Media controller card doesn't work with entity filter

### ISSUE THREAD

**Issue by Bahnburner** [home-assistant/ui-schema#82]
Attempting to specify the media-controller card for an entity within an entity-filter, Lovelace is currently throwing the following error:

    Cannot read property 'states' of undefined
    
    {
      "type": "entity-filter",
      "entities": [
        "media_player.rasplex"
      ],
      "state_filter": [
        "playing"
      ],
      "card": {
        "type": "media-control",
        "entity": "media_player.rasplex"
      }
    }

Here's the portion from my config: 

          - type: entity-filter
            entities:
              - media_player.rasplex
            state_filter:
              - 'playing'
            card: 
              type: media-control
              entity: media_player.rasplex

**Comment by c727** [comment]
```
hui-entity-filter-card TypeError: Cannot read property 'states' of undefined
    at HTMLElement.set hass [as hass] (hui-legacy-wrapper-card.js:32)
```
I'm not sure if users should abuse the filter for this, it's made for cards with multiple entities.

cc: @balloob

**Comment by Bahnburner** [comment]
Obviously the end game is to use this for all of my media players to only show them on the main view when playing.

The other option would be to allow the media-controller card to filter by state, but this method was @balloob's suggestion.

**Comment by balloob** [comment]
I like the abuse @c727
