### ISSUE TITLE
Pictures eventually require re-authentication

### ISSUE THREAD

**Issue by JesseWebDotCom** [home-assistant/ui-schema#87]
Setting HA 0.73 Lovelace picture-glance "image" to a Blue Iris camera feed (ex. http://BI_IP:BI_PORT/mjpg/CAMERA_NAME/video.mjpg?username=USER_NAME&password=USER_PASSWORD) works initially but later causes the image to disappear until eventually the browser prompts for the USER_NAME and USER_PASSWORD to the BI_IP (after which the image reappears).

This shouldn't happen since I'm providing the credentials through the url.

**Comment by c727** [comment]
We don't support camera streams there, use camera_image instead

**Comment by JesseWebDotCom** [comment]
camera_image shows images every x seconds while image shows a real time camera feed
