### ISSUE TITLE
feature request: allow icon assignment in entity objects

### ISSUE THREAD

**Issue by steve28** [home-assistant/ui-schema#88]
It would be nice to be able to specify an mdi icon in the entity objects.

**Comment by balloob** [comment]
You mean an icon override like for name?

**Comment by balloob** [comment]
We should move away from customize yaml so an override is appropriate

**Comment by c727** [comment]
What is the argument to use Lovelace instead of config entries or customize here?

**Comment by balloob** [comment]
Customize is storing icons in the state machine, we no longer want to move away from storing UI config in the state machine.

Config entries are for storing authentication of services and devices, not really appropriate for storing icons.

```yaml
- entity: sensor.air_pressure
  icon: "mdi:bla"
```

**Comment by c727** [comment]
I guess I meant entity registry then, the thing that we use to overwrite friendly name already

**Comment by c727** [comment]
... for name I can understand that you want to have different names in different cards/views. But why should the icon be different?

**Comment by balloob** [comment]
Well the question is if icon should be stored in the state machine to begin with… it's a legacy thing and probably won't go away, but it's directly tied to our frontend using MDI icons.

But you're right, what would be the use case?

**Comment by pvizeli** [comment]
I like the first idea from @balloob to store this kind of data into `entity_register` like the `name` and `alias`

**Comment by ciotlosm** [comment]
we should move away from customise. UI specific overrides should sit in Lovelace or entity registry. Entity registry works at the moment only with uuid right?

**Comment by Djebouh** [comment]
@c727 @balloob , a same object could show with different icons in different contexts (glance vs floor plan).

As a concrete example, I have customised icons of my lights to illustrate their location (mdi:glass-cocktail for the light in the bar, mdi:car for the light in the garage). It make sense for a glance view, but not for the floor plan where I would prefer all lights to show as mdi:lightbulb.
I would keep the customized light icons as the preferred ones in the registry and override only in the floor plan.

**Comment by balloob** [comment]
Convincing use case 👍 I approve of having `icon:` be added to the entity row config as an override.
