### ISSUE TITLE
hui-image does not handle camera image fetch failure

### ISSUE THREAD

**Issue by awarecan** [home-assistant/ui-schema#89]
Release 0.73.0

`hui-image` didn't handled exception when fetch camera image failure. Ideally, 

For example, if I turn off my Nest Cam, the hui-image will log following error message in console

![image](https://user-images.githubusercontent.com/7366491/42423475-b182738c-82af-11e8-9202-35ad68e05ae4.png)

And on the UI the card will collapse to just one row. The top card is the Nest Cam turned off, the bottom one is in normal state (masked most of the image).

![image](https://user-images.githubusercontent.com/7366491/42423496-24764ecc-82b0-11e8-99d8-9f86b1d573b8.png)

Ideally, I want to `hui-image` can handle this exception and fallback to image, so that I can point it to a gray place holder, says camera is off.

home-assistant/home-assistant#15051 is loosely depends on this.

**Comment by balloob** [comment]
We need to include a broken image. Preferably we keep the width and height of the previous image if available but render it with grey background and broken icon in the middle.
