### ISSUE TITLE
Feature Request: Remote Glance

### ISSUE THREAD

**Issue by jer78** [home-assistant/ui-schema#90]
I'd like to see, if possible, a remote card glance that changes the media_player based on the Harmony or other remote component.

The activities in the remote would be icons like in the picture-glance card and would allow a media_player to be displayed on the front end.

Alternatively, a dynamic media player based on a template. Depending on the template switches that are added to the media player glance card, it would change to the assigned media player.

Also, if it’s possible to add the volume controls directly in a media card, this would be a real nice to have.

**Comment by c727** [comment]
This sounds more like a backend component or build something custom using picture-elements

**Comment by jer78** [comment]
Well, the idea here is to NOT have users build something custom. Today, using a remote component requires significant amount of YAML to be of any value and it's very confusing for new users. So the suggestion was to make it simpler for the user. But if you don't think it's a good idea and just close the suggestion then...
