### ISSUE TITLE
Scenes in picture-elements cant be activated via the tap_action: toggle

### ISSUE THREAD

**Issue by lweberru** [home-assistant/ui-schema#91]
Right now it seems not to be possible to activate a scene within picture-elements without the details popup, which should be not needed for easy use.

**Comment by balloob** [comment]
Scenes are not toggle-able.

**Comment by lweberru** [comment]
yes thats the problem, so there could be another tap_action entry, like "activate", or an autodetect, that a scene cant be toggled, so it should just decide by its own to activate it instead.
