### ISSUE TITLE
Picture Highlighting of picture-glance should be also available in picture-elements

### ISSUE THREAD

**Issue by lweberru** [home-assistant/ui-schema#92]
Today the automated highlightning of the picture within picture-glance is not available in the picture-elements or vice versa it is not possible to place your lights in picture-glance. Both is nice, but you cant use both at once. Why dont merge these two? Or at least make these feature available for both cards.

**Comment by c727** [comment]
Can you explain this a bit more so that somebody can understand what you are talking about?

**Comment by lweberru** [comment]
picture glance is a component of the new lovelace component with a feature, where the picture is getting grey when the lights are off and colored when a light is on. For this to work you specify an entity which state is beeing monitored. You can even use state_image to select different images (which is also not working for me right now). I would like to get this feature also available in picture-elements. So give picture elements an "entity: ..." entry and also these state_image possibilities. Why not just combine these two elements both have positive features.

**Comment by c727** [comment]
duplicate amd WIP
