### ISSUE TITLE
ISSUE: new picture-glance card doesn't show when entity is not discovered yet/unavailable

### ISSUE THREAD

**Issue by accelle17** [home-assistant/ui-schema#93]
How to reproduce:

1. Create a new card using picture-glance type
2. Entity should be unavailable or not discovered yet before adding to the new card (I usually turn off a xiaomi wifi light using a dumb switch during weekends).
3. Reload lovelace

EDIT: HASS version 0.73 on hassbian.

**Comment by balloob** [comment]
What does it show instead?

**Comment by accelle17** [comment]
None, just the background of the page. The next card goes to another panel like it knows there should be a card before it.

**Comment by balloob** [comment]
Oh, that's broken images. Yeah, we just fixed that for 0.74.

**Comment by accelle17** [comment]
Great, will wait for the official release. Thanks!
