### ISSUE TITLE
Weather icons are the wrong colour

### ISSUE THREAD

**Issue by DubhAd** [home-assistant/ui-schema#98]
I don't know if this is really a feature request, or a bug, or... 🤷‍♂️ I suspect more feature request?

I've got a custom theme, and the text is white. Weather icons are black.

![image](https://user-images.githubusercontent.com/11191848/42600464-53bdaad4-855a-11e8-8667-65fee0b1732c.png)

There should be a feature to force weather icons to be the same colour for consistency.

**Comment by balloob** [comment]
Well, don't you define the image of the weather icon yourself? I don't think that that picture comes from Home Assistant?

**Comment by c727** [comment]
I suggest that someone should replace the SVGs with material design icons in the main code and removes the files from frontend

https://github.com/home-assistant/home-assistant-polymer/tree/master/public/images/darksky
