### ISSUE TITLE
Feature Request: Add sensors to picture glance card

### ISSUE THREAD

**Issue by jer78** [home-assistant/ui-schema#99]
Since rooms the most obvious use case for picture glance I was hoping for an ability to add sensors such as room temperature, humidity etc to the top/middle left or right side of the card. this would make better use of the card rather than have a separate glance card for sensors.

**Comment by balloob** [comment]
But there is not really space in the bottom bar to write out the value of a sensor.

**Comment by c727** [comment]
Sounds like picture-elements cards

**Comment by balloob** [comment]
Yep, picture elements is indeed the solution here.

**Comment by jer78** [comment]
The idea was something like this...

![screen shot 2018-07-12 at 3 41 32 pm](https://user-images.githubusercontent.com/1253286/42655648-bc773dac-85ea-11e8-8ed8-78862312c54e.png)
